name: default-on-push
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        services:
            kafka-server:
              image: bitnami/kafka
              ports:
                  - 9094:9094
              env:
                  KAFKA_CFG_NODE_ID: 0
                  KAFKA_CFG_PROCESS_ROLES: "controller,broker"
                  KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@localhost:9093"
                  KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094"
                  KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-server:9092,EXTERNAL://localhost:9094"
                  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT"                  
                  KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v4
              with:
                go-version: 1.22.3
            - run: sudo apt-get install libpcap-dev
            - run: go test
            - run: go build